server:
  port: 8081

hexagonal:
  client:
    address:
      url: http://localhost:8082/address

spring:
  data:
    mongodb:
      uri: mongodb+srv://arquitetura:hexagonal@offex.3d7xuv4.mongodb.net/offex?retryWrites=true&w=majority





